Failed to complete cronjob at ('*/2 * * * *', 'app.get_daily_nasdaq.main')
Traceback (most recent call last):
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/stockmarkettracker/app/get_daily_nasdaq.py", line 35, in main
    stocks_df.to_csv(f"data/{str(datetime.now())}.csv", index=False)
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/pandas/core/generic.py", line 3466, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 237, in save
    with get_handle(
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/2021-08-30 04:12:06.081490.csv'
Running 2021-08-30 04:12:01.590331
Failed to complete cronjob at ('*/2 * * * *', 'app.get_daily_nasdaq.main')
Traceback (most recent call last):
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/stockmarkettracker/app/get_daily_nasdaq.py", line 35, in main
    stocks_df.to_csv(f"data/{str(datetime.now())}.csv", index=False)
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/pandas/core/generic.py", line 3466, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 237, in save
    with get_handle(
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/2021-08-30 04:14:07.801032.csv'
Running 2021-08-30 04:14:01.433963
Failed to complete cronjob at ('*/2 * * * *', 'app.get_daily_nasdaq.main')
Traceback (most recent call last):
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/stockmarkettracker/app/get_daily_nasdaq.py", line 29, in main
    text = browser.find_element_by_tag_name('body').text
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 530, in find_element_by_tag_name
    return self.find_element(by=By.TAG_NAME, value=name)
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=92.0.4515.159)
  (Driver info: chromedriver=2.42.591059 (a3d9684d10d61aa0c45f6723b327283be1ebaad8),platform=Mac OS X 10.15.7 x86_64)

Running 2021-08-30 04:16:01.750734
Failed to complete cronjob at ('*/2 * * * *', 'app.get_daily_nasdaq.main')
Traceback (most recent call last):
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/stockmarkettracker/app/get_daily_nasdaq.py", line 35, in main
    stocks_df.to_csv(f"data/{str(datetime.now())}.csv", index=False)
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/pandas/core/generic.py", line 3466, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 237, in save
    with get_handle(
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/2021-08-30 04:18:07.356042.csv'
Running 2021-08-30 04:18:02.667790
Failed to complete cronjob at ('*/2 * * * *', 'app.get_daily_nasdaq.main')
Traceback (most recent call last):
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/stockmarkettracker/app/get_daily_nasdaq.py", line 27, in main
    browser.get(url)
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status
from unknown error: cannot determine loading status
from disconnected: received Inspector.detached event
  (Session info: chrome=92.0.4515.159)
  (Driver info: chromedriver=2.42.591059 (a3d9684d10d61aa0c45f6723b327283be1ebaad8),platform=Mac OS X 10.15.7 x86_64)

Running 2021-08-30 04:20:04.015162
Failed to complete cronjob at ('*/2 * * * *', 'app.get_daily_nasdaq.main')
Traceback (most recent call last):
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/stockmarkettracker/app/get_daily_nasdaq.py", line 29, in main
    text = browser.find_element_by_tag_name('body').text
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 530, in find_element_by_tag_name
    return self.find_element(by=By.TAG_NAME, value=name)
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/niravshah/Nirav/Github/stockmarkettracker/env/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=92.0.4515.159)
  (Driver info: chromedriver=2.42.591059 (a3d9684d10d61aa0c45f6723b327283be1ebaad8),platform=Mac OS X 10.15.7 x86_64)

Running 2021-08-30 04:22:02.475177
